# Databricks notebook source
# MAGIC %md
# MAGIC # 01 - Bronze Layer Ingestion
# MAGIC
# MAGIC Reads the raw files (as generated by `data_generator/generate_fake_data.py`,
# MAGIC uploaded into a Unity Catalog Volume) and lands them as Delta tables in the
# MAGIC **bronze** layer.
# MAGIC
# MAGIC Bronze = raw, as-landed. No cleaning, no deduping, no type-fixing here on
# MAGIC purpose - that all happens in the silver layer next. Bronze should be a
# MAGIC close-to-lossless copy of the source data, just converted into a queryable
# MAGIC table format (Delta) instead of loose files.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Config
# MAGIC
# MAGIC Keeping all paths in one place at the top, so moving from this Volume-based
# MAGIC setup to real ADLS later is a one-line change per path, not a code rewrite.

# COMMAND ----------

# Source: where the raw uploaded files live (Unity Catalog Volume)
RAW_BASE_PATH = "/Volumes/workspace/default/bronze_uploads"

CUSTOMERS_RAW_PATH = f"{RAW_BASE_PATH}/customers.csv"
PRODUCTS_RAW_PATH = f"{RAW_BASE_PATH}/products.csv"
ORDERS_RAW_PATH = f"{RAW_BASE_PATH}/all_orders.json"

# Destination: catalog.schema for the bronze Delta tables
CATALOG = "workspace"
SCHEMA = "default"

BRONZE_CUSTOMERS_TABLE = f"{CATALOG}.{SCHEMA}.bronze_customers"
BRONZE_PRODUCTS_TABLE = f"{CATALOG}.{SCHEMA}.bronze_products"
BRONZE_ORDERS_TABLE = f"{CATALOG}.{SCHEMA}.bronze_orders"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Ingest customers

# COMMAND ----------

df_customers = (
    spark.read
    .option("header", "true")
    .option("inferSchema", "true")
    .csv(CUSTOMERS_RAW_PATH)
)

print(f"customers rows: {df_customers.count()}")
df_customers.printSchema()
df_customers.display()

# COMMAND ----------

df_customers.write.format("delta").mode("overwrite").saveAsTable(BRONZE_CUSTOMERS_TABLE)
print(f"Wrote bronze table: {BRONZE_CUSTOMERS_TABLE}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Ingest products

# COMMAND ----------

df_products = (
    spark.read
    .option("header", "true")
    .option("inferSchema", "true")
    .csv(PRODUCTS_RAW_PATH)
)

print(f"products rows: {df_products.count()}")
df_products.printSchema()
df_products.display()

# COMMAND ----------

df_products.write.format("delta").mode("overwrite").saveAsTable(BRONZE_PRODUCTS_TABLE)
print(f"Wrote bronze table: {BRONZE_PRODUCTS_TABLE}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Ingest orders
# MAGIC
# MAGIC This is the messy one on purpose - duplicate `order_id`s, null
# MAGIC `customer_id`s, inconsistent `order_date` formats, and a few
# MAGIC negative/zero `amount` values are all still present here. That's
# MAGIC expected and correct for bronze - we land it as-is, and clean it in
# MAGIC the silver notebook next.

# COMMAND ----------

df_orders = spark.read.option("multiline", "true").json(ORDERS_RAW_PATH)

print(f"orders rows (raw, including duplicates): {df_orders.count()}")
df_orders.printSchema()
df_orders.display()

# COMMAND ----------

# Quick sanity check on the known data quality issues, just to confirm
# the messiness actually made it through ingestion intact.

from pyspark.sql import functions as F

null_customer_ids = df_orders.filter(F.col("customer_id").isNull()).count()
non_positive_amounts = df_orders.filter(F.col("amount") <= 0).count()
duplicate_order_ids = (
    df_orders.groupBy("order_id").count().filter(F.col("count") > 1).count()
)

print(f"Null customer_id: {null_customer_ids}")
print(f"Non-positive amount: {non_positive_amounts}")
print(f"Duplicate order_id groups: {duplicate_order_ids}")

# COMMAND ----------

df_orders.write.format("delta").mode("overwrite").saveAsTable(BRONZE_ORDERS_TABLE)
print(f"Wrote bronze table: {BRONZE_ORDERS_TABLE}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Summary
# MAGIC
# MAGIC Bronze tables created:
# MAGIC - `bronze_customers`
# MAGIC - `bronze_products`
# MAGIC - `bronze_orders`
# MAGIC
# MAGIC All three are exact, untouched copies of the source files - just now
# MAGIC living as queryable Delta tables instead of loose CSV/JSON. Next notebook
# MAGIC (`02_silver_transform.py`) reads from these three tables and produces
# MAGIC cleaned, deduplicated, properly-typed silver tables.